language: node_js # 设置语言

node_js: node # 设置相应版本

os: windows # 操作系统

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

# 邮件通知成功或是失败
notifications:
  email:
    recipients:
      - 2952068332@qq.com
      - 2498274282@qq.com
    on_success: always # default: change
    on_failure: always # default: always

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install hexo-cli -g # 安装依赖
  - chmod +x ./publish-to-master.sh  # 为shell文件添加可执行权限

install:
  - npm install # 安装hexo及插件

script:
  - hexo clean # 部署命令 清除
  - hexo g # 生成

after_script:
  - ./publish-to-master.sh # 进入静态文件目录，部署到指定仓库

branches:
  only:
  - hexo # 只监测hexo分支

env:
  global:
    - GH_REF: github.com/waldenlak/waldenlak.github.io.git #设置环境变量，更改name
